############################################
###
###       TESTING CONFIG FILE
###
############################################

########  Execution Parameters
threads: 8
mem: 60

simplejob_mem: 10
simplejob_threads: 4

large_mem: 250
large_threads: 8
assembly_threads: 8
assembly_memory: 250

runtime: #in h
  simplejob: 4
  default: 5
  assembly: 48
  long: 24

########  File Paths (Databases and Outputs)
outputDir: ''



########  Step Specific Configs
porechop_extra: ''
flye_extra:
minimap2_extra: ''
racon_extra: ''
sed_extra: ''
medaka_extra: ''
samtools_extra: ''
jgi_summarize_bam_contig_depths: ''

